/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#7B5EA7',
        'on-primary': '#ffffff',
        'primary-container': '#C9B3E8',
        'on-primary-container': '#3D1F6B',
        'inverse-primary': '#D4BBFF',
        secondary: '#A07820',
        'on-secondary': '#ffffff',
        'secondary-container': '#FFF0A0',
        'on-secondary-container': '#5C4700',
        tertiary: '#B784A7',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#F2D5ED',
        'on-tertiary-container': '#4A1F43',
        background: '#FDFCFF',
        'on-background': '#1E1B2E',
        surface: '#FDFCFF',
        'on-surface': '#1E1B2E',
        'on-surface-variant': '#5C5470',
        'surface-container': '#F2EEF9',
        'surface-container-low': '#F7F3FD',
        'surface-container-high': '#EAE3F5',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#DFD8EF',
        'surface-dim': '#DED8E8',
        'surface-bright': '#FDFCFF',
        'surface-variant': '#E8E0F0',
        'surface-tint': '#7B5EA7',
        outline: '#8A7FA0',
        'outline-variant': '#D0C4E4',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#2E2840',
        'inverse-on-surface': '#F4EEFF',
      },
      fontFamily: {
        quicksand: ['Quicksand', 'sans-serif'],
        nunito: ['"Nunito Sans"', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        card: '0 10px 30px -10px rgba(123, 94, 167, 0.12)',
        'card-hover': '0 20px 40px -15px rgba(123, 94, 167, 0.22)',
        soft: '0 4px 20px -5px rgba(123, 94, 167, 0.08)',
      },
    },
  },
  plugins: [],
}
